//////////////////////////////////////////////////////////////////////////////////////
//
// (C) Daniel Strano and the Qrack contributors 2017-2023. All rights reserved.
//
// Weed is for minimalist AI/ML inference and backprogation in the style of
// Qrack.
//
// Licensed under the GNU Lesser General Public License V3.
// See LICENSE.md in the project root or
// https://www.gnu.org/licenses/lgpl-3.0.en.html for details.

#pragma once

#include "config.h"

namespace Weed {

enum OCLAPI {
  OCL_API_UNKNOWN = 0,
  OCL_API_CLEAR_BUFFER_INT = 1,
  OCL_API_CLEAR_BUFFER_REAL = 2,
  OCL_API_FILL_ONES_INT = 3,
  OCL_API_FILL_ONES_REAL = 4,
  OCL_API_FILL_ONES_COMPLEX = 5,
  OCL_API_FILL_VALUE_INT = 6,
  OCL_API_FILL_VALUE_REAL = 7,
  OCL_API_FILL_VALUE_COMPLEX = 8,
  OCL_API_REAL_TO_COMPLEX_BUFFER = 9,
  OCL_API_REDUCE_REAL = 10,
  OCL_API_REDUCE_COMPLEX = 11,
  OCL_API_REDUCE_GRAD_REAL = 12,
  OCL_API_REDUCE_GRAD_COMPLEX = 13,
  OCL_API_REDUCE_GRAD_MIXED = 14,
  OCL_API_RELU = 15,
  OCL_API_RELU_GRAD_REAL = 16,
  OCL_API_RELU_GRAD_COMPLEX = 17,
  OCL_API_RELU_GRAD_MIXED = 18,
  OCL_API_SIGMOID = 19,
  OCL_API_SIGMOID_GRAD_REAL = 20,
  OCL_API_SIGMOID_GRAD_COMPLEX = 21,
  OCL_API_SIGMOID_GRAD_MIXED = 22,
  OCL_API_TANH = 23,
  OCL_API_TANH_GRAD_REAL = 24,
  OCL_API_TANH_GRAD_COMPLEX = 25,
  OCL_API_TANH_GRAD_MIXED = 26,
  OCL_API_MATCH_GRAD_REAL = 27,
  OCL_API_MATCH_GRAD_COMPLEX = 28,
  OCL_API_MATCH_GRAD_MIXED = 29,
  OCL_API_CLAMP = 30,
  OCL_API_CLAMP_GRAD_REAL = 31,
  OCL_API_CLAMP_GRAD_COMPLEX = 32,
  OCL_API_CLAMP_GRAD_MIXED = 33,
  OCL_API_ABS_REAL = 34,
  OCL_API_ABS_COMPLEX = 35,
  OCL_API_ABS_REAL_GRAD_REAL = 36,
  OCL_API_ABS_REAL_GRAD_COMPLEX = 37,
  OCL_API_ABS_REAL_GRAD_MIXED = 38,
  OCL_API_ABS_COMPLEX_GRAD_REAL = 39,
  OCL_API_ABS_COMPLEX_GRAD_COMPLEX = 40,
  OCL_API_ABS_COMPLEX_GRAD_MIXED = 41,
  OCL_API_ADD_REAL = 42,
  OCL_API_ADD_COMPLEX = 43,
  OCL_API_ADD_MIXED = 44,
  OCL_API_MUL_REAL = 45,
  OCL_API_MUL_COMPLEX = 46,
  OCL_API_MUL_MIXED = 47,
  OCL_API_MATMUL_REAL = 48,
  OCL_API_MATMUL_COMPLEX = 49,
  OCL_API_MATMUL_MIXED_C_LEFT = 50,
  OCL_API_MATMUL_MIXED_C_RIGHT = 51,
  OCL_API_SUB_REAL = 52,
  OCL_API_SUB_COMPLEX = 53,
  OCL_API_SUB_MIXED_C_LEFT = 54,
  OCL_API_SUB_MIXED_C_RIGHT = 55,
  OCL_API_DIV_REAL = 56,
  OCL_API_DIV_COMPLEX = 57,
  OCL_API_DIV_MIXED_C_LEFT = 58,
  OCL_API_DIV_MIXED_C_RIGHT = 59,
  OCL_API_ADD_IN_PLACE_REAL = 60,
  OCL_API_ADD_IN_PLACE_COMPLEX = 61,
  OCL_API_ADD_IN_PLACE_MIXED = 62,
  OCL_API_SUB_IN_PLACE_REAL = 63,
  OCL_API_SUB_IN_PLACE_COMPLEX = 64,
  OCL_API_SUB_IN_PLACE_MIXED = 65,
  OCL_API_POW_REAL = 66,
  OCL_API_POW_COMPLEX = 647,
  OCL_API_EXP_REAL = 68,
  OCL_API_EXP_COMPLEX = 69,
  OCL_API_LOG_REAL = 70,
  OCL_API_LOG_COMPLEX = 71,
  OCL_API_EMBEDDING_REAL = 72,
  OCL_API_EMBEDDING_COMPLEX = 73,
  OCL_API_EMBEDDING_GRAD_REAL = 74,
  OCL_API_EMBEDDING_GRAD_COMPLEX = 75,
  OCL_API_EMBEDDING_GRAD_MIXED = 76
};

} // namespace Weed
