//////////////////////////////////////////////////////////////////////////////////////
//
// (C) Daniel Strano and the Qrack contributors 2017-2023. All rights reserved.
//
// Weed is for minimalist AI/ML inference and backprogation in the style of
// Qrack.
//
// Licensed under the GNU Lesser General Public License V3.
// See LICENSE.md in the project root or
// https://www.gnu.org/licenses/lgpl-3.0.en.html for details.

#pragma once

#include "config.h"

namespace Weed {

enum OCLAPI {
  OCL_API_UNKNOWN = 0,
  OCL_API_CLEAR_BUFFER_REAL = 1,
  OCL_API_FILL_ONES_REAL = 2,
  OCL_API_FILL_ONES_COMPLEX = 3,
  OCL_API_FILL_VALUE_REAL = 4,
  OCL_API_FILL_VALUE_COMPLEX = 5,
  OCL_API_REAL_TO_COMPLEX_BUFFER = 6,
  OCL_API_REDUCE_REAL = 7,
  OCL_API_REDUCE_COMPLEX = 8,
  OCL_API_RELU = 9,
  OCL_API_RELU_GRAD_REAL = 10,
  OCL_API_RELU_GRAD_COMPLEX = 11,
  OCL_API_RELU_GRAD_MIXED = 12,
  OCL_API_SIGMOID = 13,
  OCL_API_SIGMOID_GRAD_REAL = 14,
  OCL_API_SIGMOID_GRAD_COMPLEX = 15,
  OCL_API_SIGMOID_GRAD_MIXED = 16,
  OCL_API_CLAMP = 17,
  OCL_API_CLAMP_GRAD_REAL = 18,
  OCL_API_CLAMP_GRAD_COMPLEX = 19,
  OCL_API_CLAMP_GRAD_MIXED = 20,
  OCL_API_ABS_REAL = 21,
  OCL_API_ABS_COMPLEX = 22,
  OCL_API_ABS_REAL_GRAD_REAL = 23,
  OCL_API_ABS_REAL_GRAD_COMPLEX = 24,
  OCL_API_ABS_REAL_GRAD_MIXED = 25,
  OCL_API_ABS_COMPLEX_GRAD_REAL = 26,
  OCL_API_ABS_COMPLEX_GRAD_COMPLEX = 27,
  OCL_API_ABS_COMPLEX_GRAD_MIXED = 28,
  OCL_API_ADD_REAL = 29,
  OCL_API_ADD_COMPLEX = 30,
  OCL_API_ADD_MIXED = 31,
  OCL_API_MUL_REAL = 32,
  OCL_API_MUL_COMPLEX = 33,
  OCL_API_MUL_MIXED = 34,
  OCL_API_MATMUL_REAL = 35,
  OCL_API_MATMUL_COMPLEX = 36,
  OCL_API_MATMUL_MIXED_C_LEFT = 37,
  OCL_API_MATMUL_MIXED_C_RIGHT = 38,
  OCL_API_SUB_REAL = 39,
  OCL_API_SUB_COMPLEX = 40,
  OCL_API_SUB_MIXED_C_LEFT = 41,
  OCL_API_SUB_MIXED_C_RIGHT = 42,
  OCL_API_DIV_REAL = 43,
  OCL_API_DIV_COMPLEX = 44,
  OCL_API_DIV_MIXED_C_LEFT = 45,
  OCL_API_DIV_MIXED_C_RIGHT = 46,
  OCL_API_ADD_IN_PLACE_REAL = 47,
  OCL_API_ADD_IN_PLACE_COMPLEX = 48,
  OCL_API_ADD_IN_PLACE_MIXED = 49,
  OCL_API_SUB_IN_PLACE_REAL = 50,
  OCL_API_SUB_IN_PLACE_COMPLEX = 51,
  OCL_API_SUB_IN_PLACE_MIXED = 52,
  OCL_API_POW_REAL = 53,
  OCL_API_POW_COMPLEX = 54,
  OCL_API_EXP_REAL = 55,
  OCL_API_EXP_COMPLEX = 56,
  OCL_API_LOG_REAL = 57,
  OCL_API_LOG_COMPLEX = 58
};

} // namespace Weed
