option(WEED_BLAS "Use OpenBLAS for matmul" ON)
if(WEED_BLAS)
    find_package(BLAS)
    if(BLAS_FOUND)
        target_link_libraries(weed PUBLIC ${BLAS_LIBRARIES})
        if(APPLE)
            target_compile_definitions(weed PRIVATE ACCELERATE_NEW_LAPACK)
        endif()
        if(BLAS_INCLUDE_DIRS)
            target_include_directories(weed PRIVATE ${BLAS_INCLUDE_DIRS})
        endif()
    endif()
endif()
