option(WEED_BLAS "Use OpenBLAS for matmul" ON)
if(WEED_BLAS)
    if(MSVC)
        find_package(OpenBLAS CONFIG)
        if(OpenBLAS_FOUND)
            target_include_directories(weed PUBLIC ${OpenBLAS_INCLUDE_DIRS})
            target_link_libraries(weed PUBLIC OpenBLAS::OpenBLAS)
        endif()
    else()
        find_package(BLAS)
        if(BLAS_FOUND)
            target_link_libraries(weed PUBLIC ${BLAS_LIBRARIES})
            if(APPLE)
                target_compile_definitions(weed PRIVATE ACCELERATE_NEW_LAPACK)
            endif()
        endif()
    endif()
endif()
