if(POLICY CMP0167)
    cmake_policy(SET CMP0167 NEW)
    find_package(Boost CONFIG)
else(POLICY CMP0167)
    find_package(Boost)
endif(POLICY CMP0167)
if (Boost_FOUND OR Boost_INCLUDE_DIR)
    include_directories(${Boost_INCLUDE_DIR})
    target_compile_definitions (weed PUBLIC BOOST_AVAILABLE=1)
endif (Boost_FOUND OR Boost_INCLUDE_DIR)
